import mongoose from "mongoose";
import dns from "dns";
import dotenv from "dotenv";
import Vocabulary from "../models/Vocabulary";

dotenv.config();
dns.setServers(["8.8.8.8", "8.8.4.4"]);

const seedData = [
  {
    word: "supervisor",
    type: "word",
    pronunciation: "/ˈsuː.pə.vaɪ.zər/",
    meanings: ["người giám sát"],
    partOfSpeech: "noun",
    examples: [
      { en: "My supervisor gave me positive feedback on the project.", vi: "Người giám sát đã cho tôi phản hồi tích cực về dự án." },
      { en: "The supervisor is responsible for managing the team.", vi: "Người giám sát chịu trách nhiệm quản lý nhóm." },
    ],
    topic: "work",
    level: "B1",
    synonyms: ["manager", "overseer", "boss"],
    antonyms: ["subordinate", "employee"],
    note: "Đã thành thạo.",
  },
  {
    word: "Socrates",
    type: "word",
    pronunciation: "/ˈsɒk.rə.tiːz/",
    meanings: ["Socrates – tức là cách dạy bằng đặt câu hỏi gợi mở thay vì đưa đáp án ngay"],
    partOfSpeech: "noun",
    examples: [
      { en: "The Socratic method encourages critical thinking through questions.", vi: "Phương pháp Socrates khuyến khích tư duy phản biện thông qua các câu hỏi." },
      { en: "Socrates believed that knowledge comes from within.", vi: "Socrates tin rằng kiến thức đến từ bên trong." },
    ],
    topic: "education",
    level: "B2",
    synonyms: [],
    antonyms: [],
    note: "Phương pháp Socratic: dạy bằng đặt câu hỏi gợi mở thay vì đưa đáp án ngay.",
  },
  {
    word: "Layered Architecture",
    type: "phrase",
    pronunciation: "/ˈɑː.kɪ.ˌtɛk.tʃə/",
    meanings: ["Kiến trúc phân lớp"],
    partOfSpeech: "noun",
    examples: [
      { en: "Layered architecture separates concerns into different layers.", vi: "Kiến trúc phân lớp tách biệt các mối quan tâm thành các lớp khác nhau." },
      { en: "Most web applications use a layered architecture pattern.", vi: "Hầu hết ứng dụng web sử dụng mô hình kiến trúc phân lớp." },
    ],
    topic: "technology",
    level: "B2",
    synonyms: ["multi-tier architecture", "n-tier architecture"],
    antonyms: [],
    note: "Thường gồm: Presentation, Business Logic, Data Access layers.",
  },
  {
    word: "table tissue",
    type: "word",
    pronunciation: "/ˈteɪ.bəl ˈtɪʃ.uː/",
    meanings: ["Khăn giấy để bàn"],
    partOfSpeech: "noun",
    examples: [
      { en: "Could you pass me a table tissue, please?", vi: "Bạn có thể đưa cho tôi khăn giấy để bàn được không?" },
      { en: "We need to buy more table tissues for the restaurant.", vi: "Chúng ta cần mua thêm khăn giấy để bàn cho nhà hàng." },
    ],
    topic: "daily life",
    level: "A1",
    synonyms: ["napkin", "paper napkin", "serviette"],
    antonyms: [],
    note: "",
  },
  {
    word: "Application Programming Interface",
    type: "phrase",
    pronunciation: "/aplɪˈkeɪʃ(ə)n/ /ˈpɹəʊɡɹəmɪŋ/ /ˈɪntəfeɪs/",
    meanings: ["(API) giao diện giúp các phần mềm giao tiếp với nhau"],
    partOfSpeech: "noun",
    examples: [
      { en: "We use a REST API to communicate between the frontend and backend.", vi: "Chúng tôi sử dụng REST API để giao tiếp giữa frontend và backend." },
      { en: "The Application Programming Interface allows third-party integration.", vi: "Giao diện lập trình ứng dụng cho phép tích hợp bên thứ ba." },
    ],
    topic: "technology",
    level: "B2",
    synonyms: ["API", "interface"],
    antonyms: [],
    note: "Viết tắt: API. Rất phổ biến trong lập trình.",
  },
  {
    word: "Spain",
    type: "word",
    pronunciation: "/speɪn/",
    meanings: ["Tây Ban Nha"],
    partOfSpeech: "noun",
    examples: [
      { en: "Spain is famous for its flamenco dance and bullfighting.", vi: "Tây Ban Nha nổi tiếng với điệu múa flamenco và đấu bò." },
      { en: "I want to travel to Spain next summer.", vi: "Tôi muốn đi du lịch Tây Ban Nha vào mùa hè tới." },
    ],
    topic: "geography",
    level: "A1",
    synonyms: [],
    antonyms: [],
    note: "Thủ đô: Madrid. Ngôn ngữ: Tiếng Tây Ban Nha (Spanish).",
  },
  {
    word: "France",
    type: "word",
    pronunciation: "/frɑːns/",
    meanings: ["Pháp"],
    partOfSpeech: "noun",
    examples: [
      { en: "France is known for the Eiffel Tower and fine cuisine.", vi: "Pháp nổi tiếng với Tháp Eiffel và ẩm thực tinh tế." },
      { en: "Paris is the capital of France.", vi: "Paris là thủ đô của nước Pháp." },
    ],
    topic: "geography",
    level: "A1",
    synonyms: [],
    antonyms: [],
    note: "Thủ đô: Paris. Ngôn ngữ: Tiếng Pháp (French).",
  },
  {
    word: "Portugal",
    type: "word",
    pronunciation: "/ˈpɔːr.tʃʊ.ɡəl/",
    meanings: ["Bồ Đào Nha"],
    partOfSpeech: "noun",
    examples: [
      { en: "Portugal is located on the Iberian Peninsula.", vi: "Bồ Đào Nha nằm trên bán đảo Iberia." },
      { en: "Cristiano Ronaldo is from Portugal.", vi: "Cristiano Ronaldo đến từ Bồ Đào Nha." },
    ],
    topic: "geography",
    level: "A1",
    synonyms: [],
    antonyms: [],
    note: "Thủ đô: Lisbon. Ngôn ngữ: Tiếng Bồ Đào Nha (Portuguese).",
  },
  {
    word: "wallpaper",
    type: "word",
    pronunciation: "/ˈwɔːl.peɪ.pər/",
    meanings: ["hình nền"],
    partOfSpeech: "noun",
    examples: [
      { en: "I changed the wallpaper on my phone.", vi: "Tôi đã thay hình nền trên điện thoại." },
      { en: "This wallpaper looks beautiful on the desktop.", vi: "Hình nền này trông rất đẹp trên máy tính." },
    ],
    topic: "technology",
    level: "A2",
    synonyms: ["background", "desktop background"],
    antonyms: [],
    note: "Cũng có nghĩa là giấy dán tường (trong ngữ cảnh nội thất).",
  },
  {
    word: "Auto Labeling",
    type: "phrase",
    pronunciation: "/ˈɑtoʊ/",
    meanings: ["Gán nhãn tự động"],
    partOfSpeech: "noun",
    examples: [
      { en: "Auto labeling speeds up the data annotation process.", vi: "Gán nhãn tự động giúp tăng tốc quá trình chú thích dữ liệu." },
      { en: "We use auto labeling to reduce manual work in ML pipelines.", vi: "Chúng tôi sử dụng gán nhãn tự động để giảm công việc thủ công trong quy trình ML." },
    ],
    topic: "technology",
    level: "B2",
    synonyms: ["automatic annotation", "auto annotation"],
    antonyms: ["manual labeling"],
    note: "Phổ biến trong Machine Learning và Data Science.",
  },
  {
    word: "Schema Normalization",
    type: "phrase",
    pronunciation: "/ˈskiː.mə ˌnɔː.mə.laɪˈzeɪ.ʃən/",
    meanings: ["Chuẩn hóa lược đồ dữ liệu"],
    partOfSpeech: "noun",
    examples: [
      { en: "Schema normalization helps reduce data redundancy.", vi: "Chuẩn hóa lược đồ giúp giảm dư thừa dữ liệu." },
      { en: "We applied schema normalization to our database design.", vi: "Chúng tôi áp dụng chuẩn hóa lược đồ vào thiết kế cơ sở dữ liệu." },
    ],
    topic: "technology",
    level: "B2",
    synonyms: ["database normalization"],
    antonyms: ["denormalization"],
    note: "Các mức chuẩn hóa: 1NF, 2NF, 3NF, BCNF.",
  },
  {
    word: "Data Preparation Pipeline",
    type: "phrase",
    pronunciation: "/ˈdaetə/ /pɹɛpəˈɹeɪʃən/ /ˈpaɪpˌlaɪn/",
    meanings: ["Quy trình chuẩn bị dữ liệu"],
    partOfSpeech: "noun",
    examples: [
      { en: "A data preparation pipeline automates cleaning, transforming, and loading data.", vi: "Quy trình chuẩn bị dữ liệu tự động hóa việc làm sạch, chuyển đổi và nạp dữ liệu." },
      { en: "Building a robust data preparation pipeline is essential for ML projects.", vi: "Xây dựng quy trình chuẩn bị dữ liệu mạnh mẽ là thiết yếu cho các dự án ML." },
    ],
    topic: "technology",
    level: "B2",
    synonyms: ["ETL pipeline", "data pipeline"],
    antonyms: [],
    note: "Bao gồm các bước: thu thập, làm sạch, biến đổi, và nạp dữ liệu.",
  },
  {
    word: "Machine Learning Operations",
    type: "phrase",
    pronunciation: "/məˈʃin/ /ˈlɜːnɪŋ/ /ˌɒpəˈɹeɪʃənz/",
    meanings: ["(MLOps) là tập hợp quy trình và công cụ giúp triển khai, quản lý và vận hành mô hình Machine Learning ổn định trong thực tế"],
    partOfSpeech: "noun",
    examples: [
      { en: "MLOps bridges the gap between ML development and production deployment.", vi: "MLOps thu hẹp khoảng cách giữa phát triển ML và triển khai sản phẩm." },
      { en: "Our team adopted Machine Learning Operations to streamline model delivery.", vi: "Nhóm chúng tôi áp dụng MLOps để tối ưu hóa quy trình phân phối mô hình." },
    ],
    topic: "technology",
    level: "C1",
    synonyms: ["MLOps"],
    antonyms: [],
    note: "Kết hợp ML + DevOps. Bao gồm: CI/CD cho model, monitoring, versioning.",
  },
  {
    word: "Capricorn",
    type: "word",
    pronunciation: "/ˈkæp.rɪ.kɔːrn/",
    meanings: ["Ma Kết"],
    partOfSpeech: "noun",
    examples: [
      { en: "Capricorn is the tenth sign of the zodiac.", vi: "Ma Kết là cung hoàng đạo thứ mười." },
      { en: "People born between December 22 and January 19 are Capricorns.", vi: "Những người sinh từ 22/12 đến 19/1 thuộc cung Ma Kết." },
    ],
    topic: "general",
    level: "A2",
    synonyms: [],
    antonyms: [],
    note: "Biểu tượng: con dê biển. Thuộc nhóm nguyên tố Đất (Earth).",
  },
  {
    word: "group discussion",
    type: "phrase",
    pronunciation: "/ɡɹuːp/ /dɪsˈkʊʃən/",
    meanings: ["thảo luận nhóm"],
    partOfSpeech: "noun",
    examples: [
      { en: "We had a group discussion about the new project plan.", vi: "Chúng tôi đã có buổi thảo luận nhóm về kế hoạch dự án mới." },
      { en: "Group discussion helps students develop critical thinking skills.", vi: "Thảo luận nhóm giúp sinh viên phát triển kỹ năng tư duy phản biện." },
    ],
    topic: "education",
    level: "A2",
    synonyms: ["team discussion", "panel discussion"],
    antonyms: [],
    note: "",
  },
  {
    word: "glasses case",
    type: "phrase",
    pronunciation: "/ˈɡlasɪz/ /keɪs/",
    meanings: ["hộp đựng kính", "hộp kính mắt"],
    partOfSpeech: "noun",
    examples: [
      { en: "I forgot my glasses case at the office.", vi: "Tôi để quên hộp kính mắt ở văn phòng." },
      { en: "This glasses case is made of leather.", vi: "Hộp đựng kính này làm bằng da." },
    ],
    topic: "daily life",
    level: "A1",
    synonyms: ["spectacle case", "eyeglass case"],
    antonyms: [],
    note: "",
  },
  {
    word: "Fine-tuning",
    type: "word",
    pronunciation: "/faɪn ˈtjuːnɪŋ/",
    meanings: ["là quá trình điều chỉnh một mô hình AI đã được huấn luyện sẵn để nó hoạt động tốt hơn cho một tác vụ hoặc lĩnh vực cụ thể"],
    partOfSpeech: "verb",
    examples: [
      { en: "Fine-tuning a pre-trained model can significantly improve accuracy.", vi: "Tinh chỉnh một mô hình đã huấn luyện sẵn có thể cải thiện đáng kể độ chính xác." },
      { en: "We are fine-tuning GPT for our customer support chatbot.", vi: "Chúng tôi đang tinh chỉnh GPT cho chatbot hỗ trợ khách hàng." },
    ],
    topic: "technology",
    level: "C1",
    synonyms: ["adjusting", "calibrating", "tweaking"],
    antonyms: [],
    note: "Khác với training from scratch. Fine-tuning dùng pre-trained model làm nền.",
  },
  {
    word: "Hair comb",
    type: "phrase",
    pronunciation: "/heː/ /kəʊm/",
    meanings: ["Lược chải tóc"],
    partOfSpeech: "noun",
    examples: [
      { en: "She always carries a hair comb in her bag.", vi: "Cô ấy luôn mang theo lược chải tóc trong túi." },
      { en: "I need to buy a new hair comb.", vi: "Tôi cần mua một chiếc lược chải tóc mới." },
    ],
    topic: "daily life",
    level: "A1",
    synonyms: ["comb", "brush"],
    antonyms: [],
    note: "",
  },
  {
    word: "Virtual machine",
    type: "phrase",
    pronunciation: "/ˈvɵːtʃuəl/ /məˈʃin/",
    meanings: ["(VM) – máy ảo, giả lập toàn bộ hệ điều hành"],
    partOfSpeech: "noun",
    examples: [
      { en: "I run Linux on a virtual machine inside Windows.", vi: "Tôi chạy Linux trên máy ảo bên trong Windows." },
      { en: "Virtual machines allow you to test software in isolated environments.", vi: "Máy ảo cho phép bạn kiểm thử phần mềm trong môi trường cô lập." },
    ],
    topic: "technology",
    level: "B2",
    synonyms: ["VM"],
    antonyms: [],
    note: "Khác với Container (Docker): VM giả lập toàn bộ OS, container chia sẻ kernel.",
  },
  {
    word: "Thermos",
    type: "word",
    pronunciation: "/ˈθɝ.məs/",
    meanings: ["Bình giữ nhiệt"],
    partOfSpeech: "noun",
    examples: [
      { en: "I bring a thermos of coffee to work every day.", vi: "Tôi mang theo bình giữ nhiệt cà phê đi làm mỗi ngày." },
      { en: "This thermos keeps water hot for 12 hours.", vi: "Bình giữ nhiệt này giữ nước nóng trong 12 giờ." },
    ],
    topic: "daily life",
    level: "A2",
    synonyms: ["flask", "vacuum flask", "insulated bottle"],
    antonyms: [],
    note: "Thermos cũng là tên thương hiệu, nhưng đã trở thành từ chung.",
  },
  {
    word: "Air conditioner",
    type: "phrase",
    pronunciation: "/ˈɛə kənˈdɪʃ.ən.ər/",
    meanings: ["Điều hòa không khí"],
    partOfSpeech: "noun",
    examples: [
      { en: "Please turn on the air conditioner, it's too hot.", vi: "Làm ơn bật điều hòa, trời nóng quá." },
      { en: "The air conditioner needs to be serviced regularly.", vi: "Điều hòa cần được bảo trì định kỳ." },
    ],
    topic: "daily life",
    level: "A2",
    synonyms: ["AC", "aircon", "cooling system"],
    antonyms: ["heater"],
    note: "Viết tắt: AC. Air conditioning = hệ thống điều hòa.",
  },
  {
    word: "The meeting",
    type: "phrase",
    pronunciation: "/ði/ /ˈmiːtɪŋ/",
    meanings: ["Cuộc họp"],
    partOfSpeech: "noun",
    examples: [
      { en: "The meeting will start at 9 AM.", vi: "Cuộc họp sẽ bắt đầu lúc 9 giờ sáng." },
      { en: "I have to prepare a report for the meeting.", vi: "Tôi phải chuẩn bị báo cáo cho cuộc họp." },
    ],
    topic: "work",
    level: "A1",
    synonyms: ["conference", "gathering", "session"],
    antonyms: [],
    note: "",
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI!);
    console.log("✅ Connected to MongoDB");

    const result = await Vocabulary.insertMany(seedData);
    console.log(`🌱 Seeded ${result.length} vocabulary items:`);
    result.forEach((v) => console.log(`   - ${v.word} (${v.level})`));

    await mongoose.disconnect();
    console.log("✅ Done!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seed error:", error);
    process.exit(1);
  }
}

seed();
